name: Deploy site files  

on:  
  push:  
    branches:  
      - master  
  workflow_dispatch:  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Deploy to Server  
        uses: AEnterprise/rsync-deploy@v1.0  
        with:  
          exclude: '*.pyc' # 排除.pyc文件  
          server_port: '22' # SSH端口  
          folder: ./ # 要推送的文件夹，路径相对于代码仓库的根目录  
          server_ip: ${{ secrets.SSH_HOST }} # 服务器的host名（IP或者域名）  
          username: ${{ secrets.SSH_USERNAME }} # 服务器登录名  
          server_destination: /livetvdata/html/git/ # 部署到目标文件夹  

      - name: Restart server  
        uses: appleboy/ssh-action@master  
        with:  
          host: ${{ secrets.SSH_HOST }} # 服务器地址  
          username: ${{ secrets.SSH_USERNAME }}  
          key: ${{ secrets.DEPLOY_KEY }}  
          script: |  
            #cd /home/fming/mysite/  
            #python manage.py migrate  
            cp -f /livetvdata/html/git/mylist.m3u /livetvdata/html/mylist.m3u  
            sed -i "s/tv.redrainl.site:8081/${{ secrets.NEWDOMAIN_4GTV }}/" /livetvdata/html/mylist.m3u  
            sed -i "s/tv.redrainl.site:9500/${{ secrets.NEWDOMAIN_LIVETV }}/" /livetvdata/html/mylist.m3u  
            sed -i "1s/epg.pm/tv.redrainl.site:88/" /livetvdata/html/mylist.m3u  
            sed -i "1s/epg.51zmt.top:8000/tv.redrainl.site:88/" /livetvdata/html/mylist.m3u  
            cat /livetvdata/html/4gtv_rn.m3u >> /livetvdata/html/mylist.m3u  
            bash /livetvdata/html/append_jms.sh
